## Understanding LSTM

In [1]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.layers import LSTM
#from keras.datasets import imdb
import numpy as np

max_features = 4 # 0,1,2,3 (total of 4)

#imaginate a car passing by. Your vision is '[]'. '[0]' means no car and '[color]' means car
#y2 is [class0, class1, class2, class3]

x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

print('Input shape: {}'.format(x.shape))
print('Output shape: {}'.format(y.shape))

Input shape: (6, 6, 1)
Output shape: (6,)


In [2]:
# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)
print('Output shape: {}'.format(y2.shape))

print('Build model...')
model = Sequential()
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2, input_shape=(None, 1)))
model.add(Dense(4, activation='sigmoid'))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Output shape: (6, 4)
Build model...
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [3]:
# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [4]:
print('Train...')
model.fit(x,y2,epochs=200)

Train...
Epoch 1/200
6/6 [==============================] - 1s 228ms/sample - loss: 0.6770 - accuracy: 0.7500
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6690 - accuracy: 0.7500
Epoch 3/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6569 - accuracy: 0.7500
Epoch 4/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6498 - accuracy: 0.7083
Epoch 5/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6419 - accuracy: 0.7917
Epoch 6/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6345 - accuracy: 0.7500
Epoch 7/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6293 - accuracy: 0.7500
Epoch 8/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6141 - accuracy: 0.7083
Epoch 9/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.6127 - accuracy: 0.7083
Epoch 10/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.5940 - accuracy: 0.708

6/6 [==============================] - 0s 5ms/sample - loss: 0.3930 - accuracy: 0.8750
Epoch 84/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.2745 - accuracy: 0.9167
Epoch 85/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.4116 - accuracy: 0.8750
Epoch 86/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.4379 - accuracy: 0.7500
Epoch 87/200
6/6 [==============================] - 0s 358us/sample - loss: 0.3758 - accuracy: 0.7917
Epoch 88/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.2796 - accuracy: 0.9167
Epoch 89/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.3322 - accuracy: 0.8333
Epoch 90/200
6/6 [==============================] - 0s 4ms/sample - loss: 0.3018 - accuracy: 0.9167
Epoch 91/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.2533 - accuracy: 0.9167
Epoch 92/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.3233 - accuracy: 0.8333
Epoch 93/20

Epoch 165/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.3078 - accuracy: 0.8750
Epoch 166/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.2950 - accuracy: 0.8750
Epoch 167/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.3819 - accuracy: 0.7917
Epoch 168/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.2307 - accuracy: 0.8333
Epoch 169/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.3450 - accuracy: 0.7917
Epoch 170/200
6/6 [==============================] - 0s 0s/sample - loss: 0.1775 - accuracy: 0.9167
Epoch 171/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.4813 - accuracy: 0.7083
Epoch 172/200
6/6 [==============================] - 0s 2ms/sample - loss: 0.1640 - accuracy: 1.0000
Epoch 173/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.3764 - accuracy: 0.7500
Epoch 174/200
6/6 [==============================] - 0s 3ms/sample - loss: 0.1848 - accuracy

In [5]:
def round_predict(pred):
    return np.round(pred, 0)
pred = model.predict(x)
#predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}\n",round_predict(pred))
print("Expected classes: {}\n",y2)

Predicted classes: {}
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Expected classes: {}
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [6]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[0],[0],[2],[2],[0]]] ))

2
